import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { isSystemNoise, previewSessionContent } from './content-preview.js';

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe('isSystemNoise', () => {
  it('识别两个 provider 注入的伪标签', () => {
    expect(isSystemNoise('<task-notification> agent finished </task-notification>')).toBe(true);
    expect(isSystemNoise('<system-reminder>记得写测试</system-reminder>')).toBe(true);
    expect(isSystemNoise('<environment_context>\n  <cwd>/work</cwd>')).toBe(true);
    expect(isSystemNoise('<codex_internal_context source="goal">')).toBe(true);
    expect(isSystemNoise('  <local-command-stdout>ok</local-command-stdout>')).toBe(true);
    expect(isSystemNoise('Caveat: The messages below were generated by the user')).toBe(true);
  });

  it('不误伤真人写的内容，包括普通 HTML', () => {
    expect(isSystemNoise('帮我看下这个 bug')).toBe(false);
    expect(isSystemNoise('<div>为什么这个标签没渲染</div>')).toBe(false);
    expect(isSystemNoise('<?php echo 1; ?>')).toBe(false);
    expect(isSystemNoise('a < b 的判断写错了')).toBe(false);
  });
});

describe('previewSessionContent', () => {
  it('跳过注入消息，只留真实对话', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'fleet-preview-'));
    temporaryDirectories.push(root);
    const filePath = path.join(root, 'session.jsonl');
    const lines = [
      { type: 'user', timestamp: '2026-07-30T10:00:00.000Z', message: { role: 'user', content: '<system-reminder>忽略我</system-reminder>' } },
      { type: 'user', timestamp: '2026-07-30T10:01:00.000Z', message: { role: 'user', content: '帮我改一下同步逻辑' } },
      { type: 'assistant', timestamp: '2026-07-30T10:02:00.000Z', message: { role: 'assistant', content: '好的，我先看代码' } },
    ];
    await writeFile(filePath, `${lines.map((line) => JSON.stringify(line)).join('\n')}\n`);

    const preview = await previewSessionContent(filePath);

    expect(preview.items.map((item) => item.text)).toEqual(['帮我改一下同步逻辑', '好的，我先看代码']);
    expect(preview.totalMessages).toBe(2);
  });
});
